server:
  port: 8585

spring:
  # main db
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    min-idle: 1
    max-idle: 2
    max-wait: 10000
    initial-size: 5
  # flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    create-schemas: true
    schemas: test
    baseline-on-migrate: true
    out-of-order: true

  # rabbitmq
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: /

demo:
  db:
    schema: test
